defmodule Exbee.Configuration do
  alias Exbee.{Device, ATCommandFrame}

  @params %{
    "DH" => "Destination Address High",
    "DL" => "Destination Address Low",
    "MY" => "16-bit Network Address",
    "MP" => "16-bit Parent Network Address",
    "NC" => "Number of Remaining Children",
    "SH" => "Serial Number High",
    "SL" => "Serial Number Low",
    "NI" => "Node Identifier",
    "SE" => "Source Endpoint",
    "DE" => "Destination Endpoint",
    "CI" => "Cluster ID",
    "TO" => "Transmit Options",
    "NP" => "Maximum Packet Payload Bytes",
    "DD" => "Device Type Identifier",
    "CR" => "Conflict Report",
    "CH" => "Operating Channel",
    "CE" => "Coordinator Enable",
    "ID" => "Extended PAN ID",
    "OP" => "Operating Extended PAN ID",
    "NH" => "Maximum Unicast Hops",
    "BH" => "Broadcast Hops",
    "OI" => "Operating 16-bit PAN ID",
    "NT" => "Node Discover Timeout",
    "NO" => "Network Discovery Options",
    "SC" => "Scan Channels",
    "SD" => "Scan Duration",
    "ZS" => "ZigBee Stack Profile",
    "NJ" => "Node Join Time",
    "JV" => "Channel Verification",
    "NW" => "Network Watchdog Timeout",
    "JN" => "Join Notification",
    "AR" => "Aggregate Routing Notification",
    "EE" => "Encryption Enable",
    "EO" => "Encryption Options",
    "NK" => "Network Encryption Key",
    "KY" => "Link Key",
    "PL" => "TX Power Level",
    "PM" => "Power Mode",
    "DB" => "Received Signal Strength",
    "PP" => "Peak Power",
    "AP" => "API Enable",
    "AO" => "API Options",
    "BD" => "Interface Data Rate",
    "NB" => "Parity",
    "SB" => "Stop Bits",
    "RO" => "Packetization Timeout",
    "D6" => "DIO6/RTS",
    "IR" => "I/O Sample Rate",
    "IC" => "Digital Change Detection",
    "P0" => "RSSI/PWM0 Configuration",
    "P1" => "DIO11/PWM1 Configuration",
    "P2" => "DIO12 Configuration",
    "P3" => "DIO13/DOUT Configuration",
    "P4" => "DIO14/DIN",
    "P5" => "DIO15/SPI_MISO",
    "P6" => "SPI_MOSI Configuration",
    "P7" => "DIO17/SPI_SSEL",
    "P8" => "DIO18/SPI_SCLK",
    "P9" => "DIO19/SPI_ATTN/PTI_DATA",
    "D0" => "AD0/DIO0 Configuration",
    "D1" => "AD1/DIO1/PTI_En Configuration",
    "D2" => "AD2/DIO2 Configuration",
    "D3" => "AD3/DIO3 Configuration",
    "D4" => "DIO4 Configuration",
    "D5" => "DIO5/Associate Configuration",
    "D8" => "DIO8/DTR/SLP_RQ",
    "D9" => "DIO9/ON_SLEEP",
    "LT" => "Associate LED Blink Time",
    "PR" => "Pull-up/Down Resistor Enable",
    "PD" => "Pull Up/Down Direction",
    "RP" => "RSSI PWM Timer",
    "DC" => "Device Controls",
    "DO" => "Device Options",
    "%V" => "Voltage Supply Monitoring",
    "V+" => "Voltage Supply Monitoring",
    "TP" => "Temperature",
    "VR" => "Firmware Version",
    "VL" => "Version Long",
    "HV" => "Hardware Version",
    "AI" => "Association Indication",
    "CT" => "Command Mode Timeout",
    "CN" => "Exit Command mode",
    "GT" => "Guard Times",
    "CC" => "Command Charact",
    "SM" => "Sleep Mode",
    "SN" => "Number of Cycles Between ON_SLEEP",
    "SP" => "Sleep Period",
    "ST" => "Time before Sleep",
    "SO" => "Sleep Options",
    "WH" => "Wake Host Delay",
    "PO" => "Polling Rate",
    "AC" => "Apply Changes",
    "AS" => "Active Scan",
    "WR" => "Write",
    "RE" => "Restore Defaults",
    "FR" => "Software Reset",
    "NR" => "Network Reset",
    "SI" => "Sleep Immediately",
    "CB" => "Commissioning Pushbutton",
    "&X" => "Clear Binding and Group Tables",
    "ND" => "Node Discovery",
    "DN" => "Destination Node",
    "IS" => "Force Sample"
  }

  def get_all(device) do
    Enum.each @params, fn({command, _name}) ->
      get(device, command)
    end
  end

  def get(device, command) do
    Device.send_frame(device, %ATCommandFrame{command: command})
  end
end
